### ISSUE TITLE
Exitcode 0 even if error occurs

### ISSUE THREAD

**Issue by MartinABCD** [abarker/pdfCropMargins#1]
Hi,
pdfCropMargins always exits with exitcode 0. Therefore it is not possible to determine if an error occured when calling pdfCropMargins as subprocess. 
I am using Python 3.6 on a Win10 machine.

In the file `pdfCropMargins.py` in `main()` you are capturing the `SystemExit` exception twice and don't pass on the exitcode. This problem happens on line 81 and in your function `cleanupIgnoringKeyboardInterrupt` on line 65. 
In the `SystemExit` exception block the exitcode has to be propagated manually otherwise the exitcode from the previous call to `sys.exit(..)` which causes the exception will be resetted.

In the exception handling on line 81 I would recommend to add the line `exitCode = sys.exc_info()[1]` to set the exitcode properly for `cleanupIgnoringKeyboardInterrupt(exitCode)` in the `finally` statement. And the `SystemExit` block on line 65 should be deleted.

Best regards,
Martin

**Comment by abarker** [comment]
Thanks for the report and the suggested changes.  I've cleaned up the error handling code in that module.
