### ISSUE TITLE
[Suggestion] Make GUI the default

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [abarker/pdfCropMargins#11]
The way I've been doing GUI + command line is that if someone enters no parameters, just runs the program, then I use the GUI version, versus adding the --gui flag as you have.  My thought was that if they want to use the command line, then the user likely has command line experience and will know to type --help to get more about the CLI format.

**Comment by abarker** [comment]
That seems like it would be a good idea for a new project.  With the pdfCropMargins
program I would have a few concerns about changing the default:

1. The program was originally designed as a command-line application.  Some important functionality is not currently being exposed by the GUI, and the flags weren't designed with a GUI in mind.

2. The program been around a while and existing code and workflows would break.

3. The GUI has some fairly heavy dependencies and is installed as a special
`extras_require` install feature.  If the extras are not installed the default
behavior would then necessarily be different for the same command, which would be
confusing.  As far as I know there is no way to detect which extras flags were used
during `pip` installs (and users would have to remember/know how it was installed to
predict the behavior).

One thing I've considered is adding a new entry-point script in addition to `pdf-crop-margins`.
This one would have the GUI as the default.  It would need a good command-line invocation
name.  There should probably be some kind of `--nogui` option to revert to command-line
behavior so users don't need to remember two distinct commands.

**Comment by MikeTheWatchGuy** [comment]
Thank you for that!  I hadn't thought about it being an established CLI tool.  Of course you can't break all those folks.
