### ISSUE TITLE
Met an exception.

### ISSUE THREAD

**Issue by ssfjhh** [abarker/pdfCropMargins#12]
`Unexpected error:  <class 'AttributeError'>
Error message   :  module 'signal' has no attribute 'SIGHUP'

  File "c:\python\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 92, in main
    for s in [signal.SIGABRT, signal.SIGTERM, signal.SIGHUP]:`

`import signal

dir(signal)
Out[2]: 
['CTRL_BREAK_EVENT',
 'CTRL_C_EVENT',
 'Handlers',
 'NSIG',
 'SIGABRT',
 'SIGBREAK',
 'SIGFPE',
 'SIGILL',
 'SIGINT',
 'SIGSEGV',
 'SIGTERM',
 'SIG_DFL',
 'SIG_IGN',
 'Signals',
 '_IntEnum',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_enum_to_int',
 '_int_to_enum',
 '_signal',
 'default_int_handler',
 'getsignal',
 'set_wakeup_fd',
 'signal']`

No attribute 'SIGHUP' is in the module 'signal', but I am sorry I don't know which attribute you really want to use.

**Comment by abarker** [comment]
Thanks for the report.  I recently added that code to be sure the program cleans up even when it gets a kill signal.  Apparently that signal is not implemented in Windows systems (though it is on Linux).  I've updated the code on GitHub and will push a new version to PyPI when I've tested it on Windows.

**Comment by abarker** [comment]
OK, I've pushed out a new version to PyPI so the pip installed version should now work.

I noticed that for some reason Windows is no longer able to find the fallback binary of pdftoppm when pdfCropMargins is installed via pip (though it can from the copied repo).  I'll open an issue on that separately, but in the meantime Ghostscript or pdftoppm will need to be installed.

**Comment by abarker** [comment]
Discovery of the fallback pdftoppm on Windows has now been fixed, too.
