### ISSUE TITLE
how to change the width of a particular page

### ISSUE THREAD

**Issue by sant527** [abarker/pdfCropMargins#16]
In a pdf file, one particular page is width is more than the other. I want to change the width of the page and scale the page accordingly.

Is it possible

**Comment by abarker** [comment]
There are several things you could try.

* You can use the `-pg` option to only crop a single page.  This command
   ```
   pdf-crop-margins -pg 6 -p 100 -a4 10 0 10 0 myfile.pdf
   ```
   will remove 10bp from the left and right margins on page 6 only.

* You could use the `-ms` option to set all pages to the same size but ignore the largest page in choosing that size:
   ```
   pdf-crop-margins -p 100 -ms 1 myfile.pdf
   ```

**Comment by namibj** [comment]
@sant527 
This tool does cropping. It will not set a new scale.

You could try `mutool draw -w width -o outfilename.pdf infilename.pdf` and get the width from e.g. reading the mediabox given at the end of the output of `mutool info -M infilename.pdf`, which should do what you are asking for (I have't tested it, however).

**Comment by sant527** [comment]
> There are several things you could try.
> 
> * You can use the `-pg` option to only crop a single page.  This command
>   ```
>   pdf-crop-margins -pg 6 -p 100 -a4 10 0 10 0 myfile.pdf
>   ```
>   
>   
>   will remove 10bp from the left and right margins on page 6 only.
> * You could use the `-ms` option to set all pages to the same size but ignore the largest page in choosing that size:
>   ```
>   pdf-crop-margins -p 100 -ms 1 myfile.pdf
>   ```

**Comment by sant527** [comment]
@abarker. I dont want to crop the margins of the page (which is larger). Rather set its width (that is either scale up or scale down based the width i provide w.r.t to the previous width

@namibj

> This tool does cropping. It will not set a new scale.

I think this is true. I will mutool
