### ISSUE TITLE
Index is lost after cropping PDF

### ISSUE THREAD

**Issue by ylhan** [abarker/pdfCropMargins#2]
Hi I was using your tool to crop one of my textbooks, but after cropping the PDF the original index (table of contents) is lost.

**Comment by abarker** [comment]
I assume you mean the clickable index or table of contents that appears on the left in Acrobat Reader as "bookmarks."  That information is currently not copied to the cropped document.  I have a possible fix, but it needs more testing to be sure it doesn't introduce new problems.  That part of the underlying PyPDF2 code, which is used by pdfCropMargins, seems to be buggy.

**Comment by ylhan** [comment]
Yeah that's exactly what I mean. I'd be willing to test it out for you if you want.

**Comment by abarker** [comment]
I just pushed a version which copies document catalog data to the cropped file if possible.  There are also a couple of new options for finer control over those settings, `--docCatBlacklist` and `--docCatWhitelist`.  See the `-h` help output for more info.  The "/Outlines" item holds the outline; by default it will be copied if it is there.  (This version is not up on PyPI yet.)

**Comment by abarker** [comment]
Have you gotten a chance to try the modified version?
