### ISSUE TITLE
calling pdfCropMargins from script

### ISSUE THREAD

**Issue by StevenClontz** [abarker/pdfCropMargins#20]
Is there any support for using this library from within another Python script, other than using `os` to call the program from the command line?

```
import os
os.system('pdf-crop-margins document.pdf -o cropped.pdf -p 0')
```

I tried something like the following:

```
from pdfCropMargins.main_pdfCropMargins import process_pdf_file
process_pdf_file("document.pdf","document.pdf","output.pdf")
```

but there's seemingly no way to pass the `args` to the function.

**Comment by abarker** [comment]
The package isn't really designed to be used as a library from within Python.  The right way to start it from Python is to call `main()` from the `pdfCropMargins` module (as shown in the script `pdfCropMargins.py` in the `bin` directory, an alternate way to run the program).  Just running the program from the `process_pdf_file` function is not guaranteed to clean up the large temp directory that holds the rendered PDF pages.  Unfortunately, the current `main` code always calls `exit` at the end.

To pass in `args`, an approach that's ugly but works is to call `main_crop()` but first load up the [`sys.argv`](https://docs.python.org/3/library/sys.html#sys.argv) list with the arguments you want to use.

I'll have to look at refactoring the code to make it easier to call the program multiple times from Python while keeping things cleaned up.  In the meantime, something similar to the code below could be used with Python 3.

```python
import sys, importlib, signal

from pdfCropMargins import external_program_calls
from pdfCropMargins.main_pdfCropMargins import main_crop
from pdfCropMargins.external_program_calls import cleanup_and_exit, remove_program_temp_directory

# Cleanup temp dir on signals.
for s in ["SIGABRT", "SIGTERM", "SIGHUP"]:
    if hasattr(signal, s): # Not all systems define the same signals.
        signal.signal(getattr(signal, s), cleanup_and_exit)

# Set up arguments and call the first time.
try:
    sys.argv.insert(1, "handbook.pdf")
    sys.argv.insert(1, "--gui")
    main_crop()
finally:
    remove_program_temp_directory()

# Modify arguments and call a second time.
importlib.reload(external_program_calls) # Creates a new temp directory.
try:
    del sys.argv[2]
    sys.argv.insert(2, "paper.pdf")
    main_crop()
finally:
    remove_program_temp_directory()
```

**Comment by abarker** [comment]
I refactored the code a bit and added a user-accessible Python interface.  You can now run the program with, for example:
```python
from pdfCropMargins import crop

crop(["paper1.pdf", "-s", "-v"])
crop(["paper2.pdf", "-gui", "-u", "-s", "-p", "0"])
```

Just pass `crop` the usual command-line arguments, separated in a list.  (The user's program has to handle any interrupts or `SystemExit` exceptions passed up to it.)

The new version has been pushed to GitHub, but I still haven't bumped the version number and pushed it to PyPI.

**Comment by StevenClontz** [comment]
Thanks for the quick refactor!

For now the project I have in mind is likely to implement calling your library from the command-line (since it's mixed in with a bunch of other command-line calls anyway), but once this hits PyPI I'll see about a more direct implementation.

**Comment by abarker** [comment]
The version number has now been bumped to 0.2.9 and the code has been pushed to PyPI.
