### ISSUE TITLE
Error when run with Python 3.8.6

### ISSUE THREAD

**Issue by ssfjhh** [abarker/pdfCropMargins#25]
PS C:\Users\username> pip install pdfcropmargins
Processing c:\users\username\appdata\local\pip\cache\wheels\67\04\4e\171216647760de41e8d0c4d25abde3fdefe7ef25eaad6ac135\pdfcropmargins-0.2.15-py2.py3-none-any.whl
Requirement already satisfied: pillow>=7.1.0; python_version >= "3.0.0" in c:\python\lib\site-packages (from pdfcropmargins) (7.2.0)
Requirement already satisfied: PyPDF2 in c:\python\lib\site-packages (from pdfcropmargins) (1.26.0)
Requirement already satisfied: wheel in c:\python\lib\site-packages (from pdfcropmargins) (0.35.1)
Installing collected packages: pdfcropmargins
Successfully installed pdfcropmargins-0.2.15
PS C:\Users\username> pdf-crop-margins.exe .\1.pdf a.pdf

Caught an unexpected exception in the pdfCropMargins program.
Unexpected error:  <class 'ModuleNotFoundError'>
Error message   :  No module named 'readline'

  File "c:\python\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 48, in main
    from .main_pdfCropMargins import main_crop
  File "c:\python\lib\site-packages\pdfCropMargins\main_pdfCropMargins.py", line 54, in <module>
    import readline # Makes prompts go to stdout rather than stderr.

**Comment by abarker** [comment]
Thanks for the report.  I've pushed a fixed version.  The readline module isn't available on Windows.
