### ISSUE TITLE
How to deal with this error?

### ISSUE THREAD

**Issue by ssfjhh** [abarker/pdfCropMargins#28]
```
>pdf-crop-margins --pdftoppmLocal --percentRetain 0 1.pdf -o a.pdf

Warning in pdfCropMargins: The wildcards in the path
   a.pdf
failed to expand.  Treating as literal.

Caught an unexpected exception in the pdfCropMargins program.
Unexpected error:  <class 'PyPDF2.utils.PdfReadError'>
Error message   :  Multiple definitions in dictionary at byte 0x1ed72 for key /PageMode

  File "c:\python\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 58, in main
    crop()
  File "c:\python\lib\site-packages\pdfCropMargins\pdfCropMargins.py", line 96, in crop
    main_crop(argv_list)
  File "c:\python\lib\site-packages\pdfCropMargins\main_pdfCropMargins.py", line 1397, in main_crop
    process_pdf_file(input_doc_fname, fixed_input_doc_fname, output_doc_fname)
  File "c:\python\lib\site-packages\pdfCropMargins\main_pdfCropMargins.py", line 1116, in process_pdf_file
    all_page_nums = set(range(0, input_doc.getNumPages()))
  File "c:\python\lib\site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
    self._flatten()
  File "c:\python\lib\site-packages\PyPDF2\pdf.py", line 1505, in _flatten
    catalog = self.trailer["/Root"].getObject()
  File "c:\python\lib\site-packages\PyPDF2\generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "c:\python\lib\site-packages\PyPDF2\generic.py", line 178, in getObject
    return self.pdf.getObject(self).getObject()
  File "c:\python\lib\site-packages\PyPDF2\pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "c:\python\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "c:\python\lib\site-packages\PyPDF2\generic.py", line 584, in readFromStream
    raise utils.PdfReadError("Multiple definitions in dictionary at byte %s for key %s" 
```

**Comment by abarker** [comment]
First, that initial warning should not have been issued, but it shouldn't affect the program's operation.  (I've updated the code to no longer attempt to expand possible globs in output filenames.)

The main problem seems most likely to be caused by a corrupt PDF file `1.pdf`.  Does the `pdf-crop-margins` command only fail for you on that input file, or does it fail on any PDF file?  The `PyPDF2` program, which is a library pdfCropMargins uses, is failing when trying to get the number of pages in the document.  One thing to try, if you have Ghostscript installed, is to use the pdfCropMargins option `--gsFix` to attempt to repair the document before it is cropped.

I'll update the code to give a more-informative error message in that situation.  If it is a corrupt PDF file then there's not much else to do except try to repair it.

**Comment by abarker** [comment]
FYI, I've pushed out version 1.0.1 which eliminates the false warning and should give a better error message in your case above.

**Comment by ssfjhh** [comment]
> First, that initial warning should not have been issued, but it shouldn't affect the program's operation. (I've updated the code to no longer attempt to expand possible globs in output filenames.)
> 
> The main problem seems most likely to be caused by a corrupt PDF file `1.pdf`. Does the `pdf-crop-margins` command only fail for you on that input file, or does it fail on any PDF file? The `PyPDF2` program, which is a library pdfCropMargins uses, is failing when trying to get the number of pages in the document. One thing to try, if you have Ghostscript installed, is to use the pdfCropMargins option `--gsFix` to attempt to repair the document before it is cropped.
> 
> I'll update the code to give a more-informative error message in that situation. If it is a corrupt PDF file then there's not much else to do except try to repair it.

it fails on any PDF file I input.

**Comment by ssfjhh** [comment]
With the new version you just give, I just got this error message.
```
Error in pdfCropMargins: The PyPDF2 module failed in an
attempt to read this input file:
   1.pdf

Is the file a PDF file?  If so then it may be corrupted.
If you have Ghostscript installed you can attempt to fix
the document by using the pdfCropMargins option '--gsFix'
(assuming you are not using that option already).  That option
can also convert some PostScript files to a readable format.

The error message was:
   Multiple definitions in dictionary at byte 0x1ea78 for key /PageMode

I/O Error: Couldn't open file '01.pdf'
```

**Comment by ssfjhh** [comment]
I re-generate the pdf file with autoCAD2021 on my PC at home. Now pdfCropMargins give no error message.
While the file pdfCropMargins may give error messages was generated by autoCAD2020 on my laptop in my office. I will try again tomorow.

**Comment by abarker** [comment]
Try running pdfCropMargins with the verbose `-v` option to get more diagnostic data.  I'm not sure where the `I/O Error:` message above is getting generated.  It's strange that the file name in that message is `01.pdf` rather than `1.pdf`.

**Comment by ssfjhh** [comment]
The attached 0.pdf is generated by the printer/plotter AutoCAD PDF (General Documentation).pc3 . and pdfCropMargins fails to crop it via this command:
```Powershell
pdf-crop-margins --pdftoppmLocal --percentRetain 0 -v .\0.pdf -o 00.pdf
```
The attached 1.pdf is generated by the printer/plotter Microsoft Print to PDF . and pdfCropMargins succeed to crop it via this command:
```Powershell
pdf-crop-margins --pdftoppmLocal --percentRetain 0 -v .\1.pdf -o 11.pdf
```
[0.pdf](https://github.com/abarker/pdfCropMargins/files/5534189/0.pdf)
[1.pdf](https://github.com/abarker/pdfCropMargins/files/5534190/1.pdf)
[11.pdf](https://github.com/abarker/pdfCropMargins/files/5534191/11.pdf)

```
pdf-crop-margins --pdftoppmLocal --percentRetain 0 -v .\0.pdf -o 00.pdf

Processing the PDF with pdfCropMargins (version 1.0.1)...
Python version: ('3', '9', '0')
System type: Windows

The input document's filename is:
    .\0.pdf

The output document's filename will be:
    00.pdf

The absolute pre-crops to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The percentages of margins to retain are:
    [0.0, 0.0, 0.0, 0.0]

The absolute offsets to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The uniform order statistics to apply to each margin, in units of bp, are:
    []

For the full page size, using values from the PDF box
specified by the intersection of these boxes: ['m', 'c']

Exception when trying to run this subprocess command:
   ['pdftoppm.exe', '-v']

Exception when trying to run this subprocess command:
   ['pdftoppm.exe', '-v']

Found pdftoppm program at: c:\python\lib\site-packages\pdfCropMargins\pdftoppm_windows_local\xpdf_tools_win_4_01_01\bin64\pdftoppm.exe

Error in pdfCropMargins: The PyPDF2 module failed in an
attempt to read this input file:
   .\0.pdf

Is the file a PDF file?  If so then it may be corrupted.
If you have Ghostscript installed you can attempt to fix
the document by using the pdfCropMargins option '--gsFix'
(assuming you are not using that option already).  That option
can also convert some PostScript files to a readable format.

The error message was:
   Multiple definitions in dictionary at byte 0x496 for key /PageMode
```
```
pdf-crop-margins --pdftoppmLocal --percentRetain 0 -v .\1.pdf -o 11.pdf

Processing the PDF with pdfCropMargins (version 1.0.1)...
Python version: ('3', '9', '0')
System type: Windows

The input document's filename is:
    .\1.pdf

The output document's filename will be:
    11.pdf

The absolute pre-crops to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The percentages of margins to retain are:
    [0.0, 0.0, 0.0, 0.0]

The absolute offsets to be applied to each margin, in units of bp, are:
    [0.0, 0.0, 0.0, 0.0]

The uniform order statistics to apply to each margin, in units of bp, are:
    []

For the full page size, using values from the PDF box
specified by the intersection of these boxes: ['m', 'c']

Exception when trying to run this subprocess command:
   ['pdftoppm.exe', '-v']

Exception when trying to run this subprocess command:
   ['pdftoppm.exe', '-v']

Found pdftoppm program at: c:\python\lib\site-packages\pdfCropMargins\pdftoppm_windows_local\xpdf_tools_win_4_01_01\bin64\pdftoppm.exe
PdfReadWarning: Superfluous whitespace found in object header b'1' b'0' [pdf.py:1665]
PdfReadWarning: Superfluous whitespace found in object header b'2' b'0' [pdf.py:1665]
PdfReadWarning: Superfluous whitespace found in object header b'3' b'0' [pdf.py:1665]

The input document has 1 pages.
PdfReadWarning: Superfluous whitespace found in object header b'6' b'0' [pdf.py:1665]

The document's metadata, if set:

   The Author attribute set in the input document is:
      clinku
   The Creator attribute set in the input document is:
      None
   The Producer attribute set in the input document is:
      Microsoft: Print To PDF
   The Subject attribute set in the input document is:
      None
   The Title attribute set in the input document is:
      C:\Users\clinku\Patent\HK\HK06\Drawing1 Model (1)

All the pages of the document will be cropped.

Original full page sizes, in PDF format (lbrt):
        1   rot = 0      [0, 0, 595.32001, 841.92004]

Copied these items from the document catalog:
   /Type
Skipped copy of these items from the document catalog:
   /Pages

The document was not previously cropped by pdfCropMargins.

Writing out the PDF with the CropBox and MediaBox redefined.
PdfReadWarning: Superfluous whitespace found in object header b'4' b'0' [pdf.py:1665]
PdfReadWarning: Superfluous whitespace found in object header b'5' b'0' [pdf.py:1665]

Rendering the PDF to images using the pdftoppm program,
this may take a while...

Analyzing the page images with Pillow to find bounding boxes,
using the threshold 191.  Finding the bounding box for page:

1

The bounding boxes are:
         1       [56.0301185882353, 183.98252655581948, 562.3022615462185, 689.934474584323]

New full page sizes after cropping, in PDF format (lbrt):
        1        [56.03012, 183.98253, 562.30226, 689.93447]

Writing the cropped PDF file.

Finished this run of pdfCropMargins.
```

**Comment by abarker** [comment]
I can reproduce the error on the `0.pdf` document.  It's an incorrect PDF format, but many PDF readers ignore those errors and it often doesn't cause problems.  I have a fix, setting `strict=False` in opening the PDF with PyPDF2.  I'll probably push out a new version shortly (at least as a fallback setting) but I need to consider it a little more.

If you have Ghostscript installed then using the `--gsFix` option also works to fix the file.

**Comment by abarker** [comment]
I've now pushed out version 1.0.2 with the change as above.  It will try to fix some PDFs if they have minor problems.  It works for me on the `0.pdf` file.

BTW, there's an online PDF validator at https://www.pdf-online.com/osa/validate.aspx.  File `0.pdf` fails but file `1.pdf` passes.

**Comment by ssfjhh** [comment]
> I've now pushed out version 1.0.2 with the change as above. It will try to fix some PDFs if they have minor problems. It works for me on the `0.pdf` file.
> 
> BTW, there's an online PDF validator at https://www.pdf-online.com/osa/validate.aspx. File `0.pdf` fails but file `1.pdf` passes.

Thank you for your patient reply.
I believe there is something error with the printer/plotter AutoCAD 2020 PDF (General Documentation).pc3
I will not use it in the future.

**Comment by realIK17** [comment]
Hi I am getting this error: PdfReadWarning: Invalid stream (index 2) within object 9930 0: Stream has ended unexpectedly
The -gsf command does not work. How to set strict=false? I'm pretty new to the whole linux stuff. thanks
