### ISSUE TITLE
Seperating header/footer whilst maintaining side to side widths

### ISSUE THREAD

**Issue by GitHubRulesOK** [abarker/pdfCropMargins#30]
I am finding it difficult to combine multiple functions
The aim is to auto trim vertical whitespace after clipping top and bottom printer margins but still maintain one common uniform page **width**

testing 
`pdf-crop-margins  -ap4 20 20 20 20 -u -p 0  sample.pdf`
allows to 1st trim bad edge clutter such as in scans or printer top/bottom headings
the -u p0 keeps the results as the minimum uniform width but I want to then force the heights to the minimum is there a way to fix / trim  ONLY width OR height

**Comment by abarker** [comment]
I'm not entirely sure what your aim is from your description.

If you want to end up with a uniform page width via the `-u` option then the pages need to start with the same width.  If not then you should also use the `-s` option.  The uniform option only crops the same amount from each page.

The pre-crop feature is intended for trimming edge clutter, etc., but it still counts as part of the crop.  If you don't want to pre-crop the width at all the pre-crop options should be `-ap4 0 20 0 20`, which pre-crops the top and bottom margins.

The percentRetain option `-p` also has a `-p4` variant which allow for the individual margin-cropping percentages to be set (left, bottom, right, top).

If that doesn't cover it, there's also the option of applying a second crop to the file after the first crop.

**Comment by GitHubRulesOK** [comment]
I get a good result with the pre-crop as those are absolute thus after that stage I may have (depending on source) slightly variable widths and heights
for arguments sake lets say three pages at that stage could be now including margins
450 wide by 700 high and 440 x 690 ad 460 x 690
the contents may be variable but generally around 420 wide may be acceptable for an automatic uniform width
 hence -p0 -u should cover that stage to ensure all pages are same width
at this point all 3 pages CONTENT are variable length the first may have a large lead in and the last page finish halfway down

My desire is to remove the white space lead in and lead out on all 3 pages
so to trim top and bottom at that stage  I only need -p 0 nul 0 nul thats the step where I cant seem to grasp how

**Comment by GitHubRulesOK** [comment]
OK
 I think I have not helped myself by using SumatraPDF as previewer with fitting mode on whilst run the scripts

so I get the desired result using (perhaps not the best mix)

pdfcropmargins\Portable Python-3.8.6 x64>pdf-crop-margins  -p4 100 0 100 0 sample.pdf
pdfcropmargins\Portable Python-3.8.6 x64>pdf-crop-margins -u sample.pdf

**Comment by abarker** [comment]
If you want to experiment with different settings you might try the GUI option `-gui` (assuming you installed the GUI version).  It shows a preview and allows you to interactively experiment with different settings.

**Comment by GitHubRulesOK** [comment]
Thanks, for the tips but it was my aim to find a CLI One line solution so I need to as you suggest take each step in turn along the lines of

pdf-crop-margins -ap4 0 20 0 20 -p4 100 0 100 0 sample.pdf & pdf-crop-margins -u sample_cropped.pdf & pdf-crop-margins -ap4 0 -10 0 -10 sample_cropped_cropped.pdf
