### ISSUE TITLE
'Document' object has no attribute 'isEncrypted'

### ISSUE THREAD

**Issue by tharindusathis** [abarker/pdfCropMargins#32]
When running `pdf-crop-margins -u -s -gui doc.pdf`, it gives an exception like,

```
Caught an unexpected exception in the pdfCropMargins program.
Unexpected error:  <class 'AttributeError'>
Error message   :  'Document' object has no attribute 'isEncrypted'

  File "/home/tharindu/.local/lib/python3.8/site-packages/pdfCropMargins/pdfCropMargins.py", line 58, in main
    crop()
  File "/home/tharindu/.local/lib/python3.8/site-packages/pdfCropMargins/pdfCropMargins.py", line 96, in crop
    main_crop(argv_list)
  File "/home/tharindu/.local/lib/python3.8/site-packages/pdfCropMargins/main_pdfCropMargins.py", line 1410, in main_crop
    did_crop = create_gui(input_doc_fname, fixed_input_doc_fname, output_doc_fname,
  File "/home/tharindu/.local/lib/python3.8/site-packages/pdfCropMargins/gui.py", line 311, in create_gui
    num_pages = document_pages.open_document(fixed_input_doc_fname)
  File "/home/tharindu/.local/lib/python3.8/site-packages/pdfCropMargins/pymupdf_routines.py", line 80, in open_document
    if self.document.isEncrypted:
```
I don't have an idea whether the problem is with that pdf file. However, the pdf is behaving as usual in other tools.

**Comment by abarker** [comment]
I assume it's just this one file that causes the error?  That might be a problem with PyMuPDF in handling that particular file, but it's hard to diagnose without being able to reproduce it.  It would help to have the full verbose output (by adding the `-v` option).  An example PDF file with the problem would be good, if you have or could generate a non-sensitive document like that.

As a workaround, you could try running without the GUI and using an alternate crop-calculating method such as with `-c p` to use `pdftoppm` to calculate the crops.

**Comment by tharindusathis** [comment]
Yes, actually the problem was with `pymupdf` version. Previously I had `pymupdf==1.18.8` and after downgrading to `pymupdf==1.17.0`, it works as expected. Thanks Allen.

**Comment by abarker** [comment]
Thanks for the report.  I pushed out a new version, 1.0.3, which has a temporary patch for the naming issue.  I've informed the PyMuPDF developers about the problem.
