### ISSUE TITLE
Backup doesn't works when using a filepath instead of filename

### ISSUE THREAD

**Issue by affan10** [abarker/pdfCropMargins#33]
Hi @abarker. This is indeed an amazing tool.

My use-case is that I created a .py file with the code below somewhere else and the pdfs to crop were present elsewhere. However, I'm encountering a problem when I use the following command to crop and backup a pdf file:

crop(['-ap', '12', '-p', '15', '-u', '-mo', '-su', 'old', '/path/to/some/file'])

The file gets modified correctly but no backup is created. I guess, that's because of using the file path and not using the file name. It's important for use-cases where we can't have the script file and the documents we want to modify in the same directory.

Any guidance on this one?

**Comment by abarker** [comment]
In this case the program is first writing the original output file as `file_cropped.pdf`, using the default-generated name in the current directory.  The `-mo` option then writes the backup file for the original input file to the current directory as `file_old.pdf`.  Finally, the original output file is moved to the full pathname of the input file.

The backup file is currently always written to the CWD.  Until I push out a fix the workaround would be to temporarily set the Python `cwd` value.

**Comment by affan10** [comment]
Ah, alright. Thanks for this.

**Comment by abarker** [comment]
I just pushed out a new version where the `--output` (`-o`) option can now take a directory path as an argument.  Output files will be written to that directory.  The `-mo` option also now works with that directory (and similarly if a full file path is passed as the output filename).  That is, the original cropped file will be written in the output directory.  Then the `-mo` option will update the original file path to hold the cropped file after moving the backup to the output directory with the backup filename.

**Comment by affan10** [comment]
Alright, many thanks for this. I guess I've understood it correctly how to use the new commands but would ask for an example command if needed with explanation :)

**Comment by abarker** [comment]
The command corresponding to your earlier example would be:
```python
crop(['-ap', '12', '-p', '15', '-u', '-mo', '-su', 'old', '-o', '/dir/dir/dir/', '/dir/dir/dir/file.pdf'])
```
This will write the cropped file in the directory `/dir/dir/dir` instead of in the CWD.  Then the `-mo` command will move the original pdf file to the backup name in the output directory `/dir/dir/dir`, and move the cropped file to the original filename (also in `/dir/dir/dir`, since that is its original directory).

You could alternately specify a different output directory if you wanted to keep the backup copies in a separate directory.

**Comment by affan10** [comment]
Understood. Thanks again!

**Comment by affan10** [comment]
Hey @abarker. I wanted your input on a problem I'm encountering while working with 3000+ pdf files, using pdfCropMargins.

The issue is that I have 3000+ pdf files with some of them having some noise on their edges. When I do a hardcoded pre-crop of -ap 5 on them, a lot of these files still retain that noise while for others it gets removed.

I then increased the pre-crop to 12 for those for testing and the noise was removed just fine for them. This means that some of the files required a bigger pre-crop while the rest needed a smaller one.

Is there a way to automatically do this? So that the noise on the edges is removed for all of them correctly? I know that the -p 18 command is dynamic and does the calculations and then retains 18% of the margins. But, what about the -ap 5 pre-crop?

**Comment by abarker** [comment]
The pre-crop is by definition applied before any other operation and occurs before any bounding box calculations, so it cannot really be dynamic.  One thing to consider is the `-ap4` option which allows you to specify different pre-crop amounts for the left, bottom, right, and top margins, respectively.

Sometimes using image blurring or smoothing operations and messing with the threshold can help with files like that, but from looking at your example that probably won't work well in your case.

**Comment by affan10** [comment]
The -ap4 won't work well as well because again, the pre-crop can be different for different pdf files.

Isn't there a way that pdfCropMargins could base the calculations on the actual text itself, rather than getting tripped by this noise on edges?

Also, other than pdfCropMargins, do you think I could use Ghostscript or sth else that you know off that could be helpful in mitigating this problem?

FYI: The screenshot I shared above; these lines are present on all 4 corners of the file for many pdfs.

**Comment by affan10** [comment]
> Is there some way to differentiate the set of files requiring the larger pre-crop from the ones requiring the smaller one?
No, I guess not. Not in my knowledge. They all seem the same with the same noise on the edges. It might be that their calculations are different under the hood which is why some require a bigger pre-crop.

Regarding your other points:
- Yes the larger pre-crop crops more than what is required, leading to a loss of text.
- It definitely isn't important to retain some percentage of the currently existing margins. I just want the extra margins or whitespace to go away and just add small padding to it so that it looks visually good.
- Hmmm, as far as I remember, I did try applying sth like this to the pdf with noisy edges that I shared above:
`crop(['-p', '0', '-u', '2_7-PDF_90461V_103.pdf', '-o', 'NEW_2_7-PDF_90461V_103.pdf'])`
If I remember correctly, the pdf remained the same. No changes were seen.

I will test your new suggestions but would be great if you could shed some light on this comment is as well.

**Comment by affan10** [comment]
I did some quick testing and used this simple command:
`crop(['-p', '0', '2_7-PDF_90461V_103.pdf', '-o', 'NEW_2_7-PDF_90461V_103.pdf'])`

The results are attached for you. The command behaves differently for both the pdfs. I've attached before-crop and after-crop screenshots of only the first pages of the files The pdf that did not change at all, is representative of those files that require a bigger pre-crop while the other one for those that required a smaller pre-crop.
<img width="625" alt="Screenshot 2021-03-09 at 7 40 03 PM" src="https://user-images.githubusercontent.com/22591256/110487601-8cb38580-810f-11eb-99af-2c55d5d96743.png">
<img width="627" alt="Screenshot 2021-03-09 at 7 42 37 PM" src="https://user-images.githubusercontent.com/22591256/110487767-b7054300-810f-11eb-8c73-01b52e742fdc.png">
<img width="622" alt="Screenshot 2021-03-09 at 7 40 31 PM" src="https://user-images.githubusercontent.com/22591256/110487815-c1bfd800-810f-11eb-9789-43cee4c6e390.png">
<img width="711" alt="Screenshot 2021-03-09 at 7 43 05 PM" src="https://user-images.githubusercontent.com/22591256/110487838-c6848c00-810f-11eb-9608-9bd84c418ff6.png">

**Comment by abarker** [comment]
In the command you'll still need to do a pre-crop in order to remove the corner obstructions.  Using `-p 0` crops tightly to the calculated bounding box, which will include the corner "text."  I'm surprised the corner obstructions were removed on p. 11 without a pre-crop.  It might be because the resolution of the rendering was low relative to the width of the corner-marking lines.

What I might try is to only pre-crop either the left and right margins (e.g., `-ap4 9 0 10 0`) or else only pre-crop the top and bottom margins (e.g., `-ap4 0 10 0 9`), whichever works better.  Test this with `-p 100`, keeping all the margin percentage, and find the approximate smallest pair of pre-crop values that remove all of the corner obstruction markings in both documents but leave almost all of the rest of the margins (and do not crop any wanted text).  Then use those `-ap4` pre-crop settings with whatever `-p` values you prefer (one idea is `-p 0 -ap4 10 10 10 10`).  You can experiment with this easily in the GUI to find parameters.

**Comment by affan10** [comment]
Okay thanks for these suggestions. I'll test these and then come back. Thanks for being so prompt. I really believe that this tool is the best one out there for use-cases like mine and your quick assistance / guidance is the icing on the cake!

**Comment by affan10** [comment]
Okay so I did some testing and I may have found a sweet spot for my pdf files.

I couldn't apply a pre-crop to just the bottom and top or the left and right because the corner markings weren't getting removed properly. So I had to crop off all of them. This is what I did:

```
crop(['-ap4', '12', '12', '12', '12', '-p', '100', '1_7-PDF_24141D_107.pdf', '-o', 'NEW_1_7-PDF_24141D_107.pdf'])
crop(['-p', '18', '-u', '-s', 'NEW_1_7-PDF_24141D_107.pdf', '-o', 'LATEST_1_7-PDF_24141D_107.pdf'])
```

Doing this directly also seems to accomplish the same thing:
`crop(['-ap4', '12', '12', '12', '12', '-p', '18', '-u', '-s', '1_7-PDF_24141D_107.pdf', '-o', 'NEW_1_7-PDF_24141D_107.pdf'])`

This is working splendidly for the 3 different pdfs I tested for. This might after all be the solution I was looking for!

**Comment by abarker** [comment]
I'm glad you found some parameter settings that work for your use-case.

**Comment by affan10** [comment]
Thanks. Need your opinion.

I tested locally with these two commands:

Combination of these two:
```
crop(['-ap4', '12', '12', '12', '12', '-p', '100', '1_7-PDF_24141D_107.pdf', '-o', 'NEW_1_7-PDF_24141D_107.pdf'])
crop(['-p', '18', '-u', '-s', 'NEW_1_7-PDF_24141D_107.pdf', '-o', 'LATEST_1_7-PDF_24141D_107.pdf'])
```

And this:
`crop(['-ap4', '12', '12', '12', '12', '-p', '18', '-u', '-s', '1_7-PDF_24141D_107.pdf', '-o', 'NEW_1_7-PDF_24141D_107.pdf'])`

Since I'm working with 3000+ pdf files and would need to run this for production, I was wondering which of the commands I posted above are "safe" per-se. By safe I mean, which involve no risk of losing some text due to the pre-crop?

I see that both the commands produce the same results, but I'm guessing that they both work differently under the hood. Is it possible that the first command provides some sort of safety with regards to the pre-crop and loss of text compared to the second one?

**Comment by abarker** [comment]
The combined command does the same thing as the two commands.

Pre-crops cannot be safe, as they are intended to remove some unwanted text.  The `-p` command is safe as long as the percentage is not negative.  The `-s` command is safe since it only increases the size of some pages to make them all the same.  The `-u` command is safe provided the other options used in the command are safe, since it takes the smaller of those crops over the pages.
