### ISSUE TITLE
Keep center/maintain symmetry after automated cropping

### ISSUE THREAD

**Issue by jonasallgeier** [abarker/pdfCropMargins#34]
I am really glad I found this tool, it seems to be a perfect solution to my problems regarding automated cropping. However, there is one thing I could not figure out: in some cases, the croppable amount of a pdf is not the same for the left and right sides (margins not equal), but I would like the cropped pdf to still have the same horizontal center point. Therefore, the cropping amount would need to be the minimum of the left and right margins. Is that already implemented in some way?

**Comment by abarker** [comment]
Unfortunately that functionality is not currently implemented.

**Comment by abarker** [comment]
Check out the new version 1.1.8.  Two new options,  `--keepHorizCenter` (`-khz`) and `--keepVertCenter` (`-kvc`) have been added. They force equal cropping on the left and right or top and bottom pages, respectively.
