### ISSUE TITLE
Is it possible to use the tool entirely in-memory

### ISSUE THREAD

**Issue by TheCodeSummoner** [abarker/pdfCropMargins#35]
Hi!

I'm wondering if I can use the tool without the file system.

More specifically, I'd like my input to be bytes, my output to be bytes, and also make sure no temporary/intermediate files are created in the process.

This is because I am using `wkhtmltopdf`'s Python wrapper to render PDF-s from HTML templates. I am setting `page-height` to be something astronomically high to make sure I can generate a single-page (very long) PDF file, and then trim the bottom white space as much as I need.

I'd like to say something like:
```python
result_bytes = crop(["-p4", "100", "0", "100", "100", "-a4", "0", "-28", "0", "0", input_bytes])
```

It doesn't seem to be supported by default, but perhaps I am missing something or there is a known approach to solve such issues?

**Comment by TheCodeSummoner** [comment]
For instance, if there was a function which accepted a `PdfFileReader` object (and e.g. page height, if it can't get it from the PDF file in bytes format) and returned a `PdfFileWriter` object, it would match my needs, as based on the docs I should be able to pass BytesIO to them, I think.

**Comment by abarker** [comment]
It currently isn't possible to use the program entirely in-memory.  The PDF file is always rewritten to a temp directory on disk to implement the pre-cropping option, and there is no option to take a `PdfFileReader` and return a `PdfFileWriter`.

As a workaround you could possibly create a ramdisk for the input and output PDFs, and set Python's `TMPDIR` environment variable there, too.

**Comment by TheCodeSummoner** [comment]
Thanks. That's what I've figured from the source code.

Hopefully, I can figure out a workaround at some point.
