### ISSUE TITLE
GUI support for MacOS

### ISSUE THREAD

**Issue by yratof** [abarker/pdfCropMargins#37]
```
➜  ~ pip install pdfCropMargins[gui] --user --upgrade
➜ no matches found: pdfCropMargins[gui]
```

the `[gui]` part of the install fails, not sure if there is a macOS version for the gui available?

**Comment by abarker** [comment]
I'm not sure what the problem is there.  I don't have a Mac to test on.  Does the ordinary install work, without the `[gui]` part?  If so, the `[gui]` part just installs extra packages which you can do as:
```
pip install PySimpleGUI PyMuPDF
```

**Comment by abarker** [comment]
The GUI dependencies are now part of the ordinary install, so you no longer need to include the `[gui]` part.
