### ISSUE TITLE
Incompatible with PyMuPDF (fitz) 1.20.0

### ISSUE THREAD

**Issue by nyanpasu64** [abarker/pdfCropMargins#38]
PyMuPDF renamed a large number of methods, and 1.20 [removed all historical method aliases](https://pymupdf.readthedocs.io/en/latest/znames.html) (breaking semver but shhhh...). According to the [changelog](https://pymupdf.readthedocs.io/en/latest/changes.html), 1.20.0 was released a mere 4 days ago on 2022-06-15, but is picked by default by Pip when installing the package (and pdfCropMargins does not pin dependencies).

When running pdf-crop-margins's CLI with `pdfCropMargins[gui]` installed (bringing the optional PyMuPDF dependency), it fails calling several PyMuPDF methods:

- Page.getDisplayList() -> get_displaylist()
- Pixmap.setResolution() -> set_dpi()
- Pixmap.getImageData() -> tobytes()

There may be more renamed methods you call, but changing these 3 calls was sufficient to make the CLI work. To make the GUI start up and load (and possibly save) a PDF file, I had to change more occurrences of getDisplayList and getImageData. If that isn't enough, a full list of renamed methods is at https://pymupdf.readthedocs.io/en/latest/znames.html.

Can you change to the new names, or do you have to preserve compatibility with the old PyMuPDF by probing the presence of the new names?

----

And additionally the PDF shown on the GUI was rotated by 180 degrees (reproduced on two PDF files), although the actual cropping is performed correctly. Is this a known bug?

**Comment by abarker** [comment]
Thanks for the bug report.  I've changed the method calls to match the new convention and updated the PyMuPDF requirement to 1.20.0 for new installs.  I've pushed out a new version, 1.0.7, with the changes.

After the changes the GUI seems to work fine for me on Linux.  Are you still seeing a rotated image?

**Comment by nyanpasu64** [comment]
According to znames.html, think 1.18.4 and 1.19 fully support the new names. I don't know the oldest version that supports all names you use, and I'll have to check one I get back to my computer. I will test the new release then too.

**Comment by nyanpasu64** [comment]
TBH I'd just set the minimum requirement to 1.19.0, rather than scrounging for the first supported API version.

When I install with `pipx install pdfCropMargins[gui]`, and run `pdf-crop-margins -gui UCAM-CL-TR-949.pdf`, I still get a rotated image:

![Screenshot_20220621_002255_pdfCropMargins: aposd2ndEdExtract pdf](https://user-images.githubusercontent.com/913957/174740482-546088d7-d5ab-43d9-a08c-0796448de729.png)

This happens on every PDF file I've tested so far.

**Comment by abarker** [comment]
I just set the requirement to 1.20.0 to be safe.

I'm not getting the upside-down pages.  Also, that page looks very small compared to the size of the widgets.  Could you post the terminal output of the verbose version of the command, with the `-v` option?  It has more diagnostic information on it.

**Comment by abarker** [comment]
Could you include the output from cropping the document, also?  It will show the page sizes and rotations that are detected.

**Comment by abarker** [comment]
That output looks normal.  This seems to be a new bug, but if it was working fine before you upgraded PyMuPDF then it is probably related.  If you revert temporarily to an earlier version of PyMuPDF (including the earlier, compatible pdfcropmargins) does it work again?  Be sure your versions of pysimplegui and pypdf2 are also up-to-date.

So far no one else has reported this issue.

**Comment by nyanpasu64** [comment]
Not sure what's wrong, I think I could debug if I wanted but I don't feel like doing so. The main issue is resolved so I'll close the bug.

**Comment by abarker** [comment]
Feel free to open a new issue should you come across more info about the inverted pages.
