### ISSUE TITLE
PdfReadError can not be imported from PyPDF2.utils since PyPDF2 1.27.6

### ISSUE THREAD

**Issue by BPSoos** [abarker/pdfCropMargins#41]
Hello, 

I have encountered the following error message:
```
Error in pdfCropMargins: No system PyPDF2 Python package
was found.  Reinstall pdfCropMargins via pip or install that
dependency ('pip install pypdf2').
```
I have found out that this is caused by line 71 from `main_pdfCropMargins.py`:
```
from PyPDF2.utils import PdfReadError
```
PdfReadError has been moved to PyPDF2.errors since 1.27.6: [see the changelog](https://github.com/py-pdf/PyPDF2/compare/1.27.5...1.27.6)

Modifying the line to the one below helped me solve the issue. Maybe we could do some version checking before the import?
```
from PyPDF2.errors import PdfReadError
```

BR,
Peter

**Comment by abarker** [comment]
Have you upgraded your versions of PyPDF2 and pdfCropMargins to the latest versions?  This sounds like the bug that was fixed in https://github.com/abarker/pdfCropMargins/issues/36.

**Comment by BPSoos** [comment]
Thanks @abarker, I have missed that my pdfCropMargins was out of date. For some reason I can't seem to update with pip to the latest version, but now I see that this bug was already fixed in a newer version. I think we can close this issue.

**Comment by abarker** [comment]
The latest version should be pdfCropMargins-1.0.9.  Just using:
```bash
pip install -U pdfcropmargins
```
works for me to do the upgrade.
