### ISSUE TITLE
Blank output PDF

### ISSUE THREAD

**Issue by oawd** [abarker/pdfCropMargins#43]
I have used this program and another program (Briss 2.0 [GitHub page](https://github.com/mbaeuerle/Briss-2.0)) on the same pdf file.
With Briss I could crop it and the output PDF is technically fine. But I prefer the program pdfCropMargins, because it allows to enter crop values and to give an identical page size to each page.

But pdfCropMargins doesn't work on the PDF. Its output is a white pdf without any content but with the same amount of pages as the input PDF.
The pdfCropMargins gui produces a crop preview that is fine. The automatic cropping of the PDF works in the preview. But when I use the command-line I get this blank output PDF no matter whether I use automatic or manual settings.

**Comment by abarker** [comment]
I would need more information to be able to do anything about this.  Does pdfCropMargins do this on all PDF files or only on some?  Are there any example PDFs which fail that you could link?

What command are you using to launch pdfCropMargins from the command line?  Add the `-v` verbose option and copy and paste the command and the output so I can try to diagnose what's going wrong.

**Comment by oawd** [comment]
The problem also happens with other PDF files. I could test a PDF file of which you know that it works.

I have downloaded a sample PDF from [here](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) and this file also causes the problem. I have put the log file and the output PDF into [this](https://github.com/oawd/filesforissue43) repository.

For the testing I did use the command
` pdf-crop-margins "input PDF path" -o "output PDF path" -v -s -u`


Also, my operating system is Windows 10. The python version is 3.10.5 .

**Comment by abarker** [comment]
It would help if you posted a copy/paste of the output of the above verbose command after running on such a file.  That will provide much more diagnostic information.  The commands worked for me in Linux so far, but Linux doesn't support Adobe Reader.

**Comment by abarker** [comment]
I tested the example file on Windows 10 with a fresh copy of Adobe Reader and could reproduce the bug.  I tried several different options to pdfCropMargins to fix it, but none worked.  The document is showing a huge zoom size, and changing that results in the error "There was a problem reading this document (14)".  Ctrl-clicking the OK gives further info: "Expected a dict object."

There are a lot of web hits on those errors.  This page seems to be the same problem, and they discuss some possible workarounds: https://community.adobe.com/t5/acrobat-reader-discussions/there-was-a-problem-reading-this-document-14/m-p/9208676

If you have Ghostscript installed, I could repair the cropped file with this command:
```bash
gs -o repaired_Loren_ipsum.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress cropped_Lorem_ipsum.pdf
```

**Comment by oawd** [comment]
Thank you. This command has worked.
As a short side note: In my Windows installation of Ghostscript I had to use the command gswin64 instead of gs .

With about a thousand pages, as one poster in the thread you have linked says, the PDF specification is quite long. I can understand if you don't find out what has to be fixed so that the original output PDFs don't get this error.
But I am glad that there is this workaround. I will now take some time to dive into the settings of pdfCropMargins :-) .

**Comment by abarker** [comment]
Try the new version pdfCropMargins 1.1.13.  For me it seems to fix the issue with viewing the example file you posted in Acrobat reader after cropping.
