### ISSUE TITLE
Inverted image preview in GUI, due to negative image width

### ISSUE THREAD

**Issue by nyanpasu64** [abarker/pdfCropMargins#48]
On Linux, when I run `pdfcropmargins -gui FILE`, the preview image of each page is rotated by 180 degrees.

![Screenshot_20230215_170709_pdfCropMargins: 2017-12-Gareus-Lat pdf](https://user-images.githubusercontent.com/913957/219232518-08f30ff4-4819-42e4-a698-af3008e53d5a.png)

Why does this happen?

- Upon GUI startup, [`create_gui()` calls](https://github.com/abarker/pdfCropMargins/blob/5417db2f44a502ffc1cdad03cd9d564c90999446/src/pdfCropMargins/gui.py#L944) `max_image_size = get_usable_image_size(window, im_wid, im_ht, left_pixels)`.
- `get_usable_image_size`:
	- `usable_width, usable_height = get_window_size(window)`
	- `get_window_size`:
		- `width, height = get_window_size_tk()` returns (200, 200)
			- I'm running on kwin_x11 with 100% display scaling but 120 X11 DPI.
			- The actual window which appears is larger than 200x200, closer to 794x789.
		- (multiply by 0.95, unimportant)
	- `win_width, win_height = window.Size` = 916x789 (not sure what's going on here!)
	- `usable_im_width, usable_im_height = (usable_width - non_im_width-left_pixels, usable_height - non_im_height)` and now `usable_im_width` is -251!
- Afterwards you fetch the PDF page (as a P6 PPM, rotated 180 degrees because of a negative width) and write it into image_element (though `sg.Image` says "Should be a GIF or a PNG only", but PPM works anyway).

I'm guessing the issue is that `get_window_size_tk` calls `root.winfo_width()/winfo_height()` which returns 200x200, but this is smaller than the actual window from `window.Size`. This throws off the subsequent calculations (I didn't verify whether they're correct or not).

I don't know if `root.winfo_width()` is broken, or if you're calling it at a time it's not defined to be valid, or if you're not setting up the window correctly to measure what you want. I don't know how to fix this bug.

```py
def get_window_size_tk():
    """Use tk to get an approximation to the usable screen area."""
```

Why does the function say "window size" but the docstring say "screen area"?

```py
            # Go to fullscreen mode to get screen size.  This seems to work with
            # multiple monitors (which otherwise get counted at a combined size).
            root.attributes("-alpha", 0) # Invisible on most systems.
            #root.attributes("-fullscreen", True) # Set to actual full-screen size.
```

The comments say you enter fullscreen to measure screen(?) size, but you never actually do because it's commented out.

Latest commit e8d592825b14e65390edfb526a94a8be088f27f7.

**Comment by abarker** [comment]
Have you tried running the program with a window manager other than `kwin_x11`?  The displayed preview is very small (as well as upside-down).

The "-fullscreen" line is commented out because the code actually uses the "-zoomed" attribute in the next line to go to full screen.  You could try swapping those lines to see if that makes a difference.  Either one seems to work for me on Ubuntu with Cinnamon, but when I comment them both out I get the same kind of small, inverted output you are reporting.

**Comment by nyanpasu64** [comment]
For reference:

https://github.com/abarker/pdfCropMargins/blob/5417db2f44a502ffc1cdad03cd9d564c90999446/src/pdfCropMargins/gui.py#L1230-L1243

On Xfce, I get some odd flickering during startup, but a normal PDF/window size:

https://user-images.githubusercontent.com/913957/219256396-05c6ae84-e0b4-41d0-96d9-c16cdefbf2f0.mp4

On KDE, with both -zoomed *and* -fullscreen, and with or without -type splash, I get a small window and upside-down PDF.

Interestingly, https://www.tcl.tk/man/tcl/TkCmd/wm.html#M34 says:

> On X11, changes to window attributes are performed asynchronously. Querying the value of an attribute returns the current state, which will not be the same as the value most recently set if the window manager has not yet processed the request or if it does not support the attribute.

Not sure what's going wrong, or how to properly check the maximized size. Uncommenting `root.update()` before `root.update_idletasks()` didn't fix the window positioning on KDE, and replacing `update_idletasks` with `update` didn't break Xfce . Should you fall back to the `winfo_screenwidth` path, or does that return too large of a size on multi-monitor setups?

**Comment by abarker** [comment]
Using `winfo_screenwidth` returns too large a size with multiple monitors.

You can test the maximized size by adding the line `import time; time.sleep(10)` just before the `elif` at the end of that conditional block.  The full screen should be set to gray for ten seconds if the maximized size is working.

It may be that `kwin_x11` doesn't implement tkinter maximization, in which case some fallback should be set.  Just using the default window size would be better than the inverted version.

**Comment by nyanpasu64** [comment]
```py
            import time
            time.sleep(5)
            #root.update()
            root.update_idletasks() # This works in place of .update, on Linux.
            time.sleep(5)
```

Before update_idletasks, I get an invisible main GUI window, which nonetheless takes focus when it appears, has a taskbar icon, blocks mouse clicks, and can be moved around with Super+drag.

After, I get a 200x200 gray square in the center of my screen, which disappears when clicked on, so I couldn't focus it and take a screenshot. I *was* able to use GIMP in "screenshot window under click" mode to take a picture and verify it was 200x200.

Commenting out `root.attributes("-type", "splash")` makes the window take up my full screen, but `winfo_screenwidth/height` is still 200x200 (both if I leave the window untouched, or if I unmaximize and tile it to the side).

If I add `update()` and `update_idletasks()` *after* sleeping, the program sees the maximized window size. If I only `update_idletasks()` it still sees 200x200.

I found that the minimum changes needed to properly probe screen size on KDE is to remove `-type splash` and replace `update_idletasks` with `update`. Sleeping for wall-clock time is not needed. Unfortunately this causes a flash of maximized window when the program opens.

I still feel this code is quite "implementation detail, subject to change" or nondeterministic behavior. It may be necessary to find an alternative way of probing current screen size using the xrandr APIs, an alternative Tk API (perhaps look in https://stackoverflow.com/q/3949844 or https://stackoverflow.com/q/3129322 eg. https://stackoverflow.com/a/56913005), or rewrite in Qt or something.

**Comment by abarker** [comment]
The code is definitely kind of a hack, but as far as I know tkinter doesn't have a good way to work with multiple monitors.  I've thought about using xrandr, but that would probably also result in some portability problems such as with people using Wayland.

I modified `get_usable_image_size` with a sanity-check fallback to make sure the suggested size isn't smaller than the existing default size.  Still testing, though, and haven't yet pushed it to PyPI.

**Comment by abarker** [comment]
I pushed the new version 1.1.15 of pdfCropMargins to PyPI.  Try it and see if it fixes your problem.  I added a fallback for when the sizing seems to fail.  I also rewrote some of the event loop so that windows can now be dragged to a larger size and the PDF preview will be properly updated.

**Comment by abarker** [comment]
The newest version 1.1.18 has the option e.g. `--screenRes 1024x728` which can be passed the actual screen resolution for when the detection code fails.  You can also now set the GUI font size.
