### ISSUE TITLE
toc outline shown correct but not valid to jump in some softwares 

### ISSUE THREAD

**Issue by czg-sci-42ver** [abarker/pdfCropMargins#49]
valid in saladict,acrobat，zotero
not valid in evince，chrome，okular
what reasons may result in this

**Comment by abarker** [comment]
Do the TOC outline links work correctly in all the above viewers on the PDF before it is cropped?

The PDF specification is quite complex.  Different viewers work differently, and the packages like PyPDF that pdfCropMargins uses can produce code that is not up to spec.

**Comment by czg-sci-42ver** [comment]
yes they are valid before cropping
thanks for your answer, maybe my demands are a little excessive

**Comment by Thomas-Lemm** [comment]
I can confirm the problem (TOC without links) for the fedora pdf viewing application (evince) and the remarkable tablet (the latter reboots upon trying to jump to a page via TOC)

**Comment by abarker** [comment]
Try the new version 2.0.0.  The PyPDF dependency has been removed. The program now uses PyMuPDF for all internal operations.

**Comment by Thomas-Lemm** [comment]
Allen, thanks for the update. I can confirm that the problem with missing pdf- internal links / references (I'm not sure about proper pdf terminology) has vanished with the update for the evince pdf viewer.
