### ISSUE TITLE
Feature require: remove header and footer

### ISSUE THREAD

**Issue by prehistoric-penguin** [abarker/pdfCropMargins#5]
Hi, I found your project is so useful. I think is't better to provide function to remove header and footer automatically. Thanks!

**Comment by abarker** [comment]
Have you tried the `-p4` option?  It allows you to set the percent of margin retained for each edge individually.  The order is left, bottom, right, top, so you can use something like `-p4 100 10 100 10` to only crop the tops and bottoms of pages.  The `-a4` option is similar, but sets absolute crop amounts for each margin individually.

**Comment by prehistoric-penguin** [comment]
Thanks for your tips, I think your suggestion will be fine. But it would be better to have a automatically mechanism.

**Comment by abarker** [comment]
One option is to write a simple shell script that calls `pdf-crop-margins` with whatever arguments you prefer (and which takes the rest of the arguments from the command line).  There are two simple example files for Bash and Windows, called `crop`, in the directory `https://github.com/abarker/pdfCropMargins/tree/master/bin`.

**Comment by prehistoric-penguin** [comment]
Thank you so much, I will close this issue.
