### ISSUE TITLE
Set custom bounding box

### ISSUE THREAD

**Issue by metinmayi** [abarker/pdfCropMargins#53]
In PDFCrop there was an option to set a custom bounding box: --bbox.
```
  --bbox "<left> <bottom> <right> <top>"                       ($::opt_bbox)
                      override bounding box found by Ghostscript
                      with origin at the lower left corner
```
Is there any equivalent with pdfCropMargins?

I checked the documentation but did not find anything.

**Comment by abarker** [comment]
No, there's currently not an option to do that.

**Comment by abarker** [comment]
Try the new version 2.0.2.  There is a new option ``--setSamePageSize`` (``-ssp``) which takes four floats as an option, to use as the ``--samePageSize`` box rather than calculating it.  With the cropping percentage set to 100 and no other options it should be equivalent.
