### ISSUE TITLE
Release git tags

### ISSUE THREAD

**Issue by nicolas-graves** [abarker/pdfCropMargins#55]
Hi! 
Some package managers need to build the packages from source, thus needing to look at the specific commit used for the pypi release. 
If that's not a lot more work for you, could you start using tags for pointing to the commit of releases ? 

Thanks!

**Comment by abarker** [comment]
Ok.

**Comment by nicolas-graves** [comment]
I see you do that well, now, big thanks.  Closing the issue which is not relevant anymore!
