### ISSUE TITLE
Evince has problems with the output. A bug in Evince?

### ISSUE THREAD

**Issue by v217** [abarker/pdfCropMargins#56]
Hi, the gnome pdf reader `evince` has problems with some docs. 
Running 
```sh
wget -c https://beej.us/guide/bgnet/pdf/bgnet_usl_c_1.pdf
pdfcropmargins -s bgnet_usl_c_1.pdf
```
I get these Errors:
```
Warning in pdfCropMargins: The cropbox could not be written to page 1.  The error is:
   CropBox not in MediaBox
....
```
Evince is not able to show the pdf. Is this a bug in Evince? But e.g. the builtin pdf-reader of chrome has no problems. 

My question is: Is there a tool which I can run on the output of pdfcropmargins to make it compatible with more (buggier) pdf-readers?

Thanks!

**Comment by abarker** [comment]
I'm not getting the CropBox warning on Linux, but the result is still screwed up in Evince.

If you have Ghostscript installed you can try using the `--gsFix` option.  I've needed to use it in some cases, and it seems to work in this case.  According to the metadata the PDF was created with Pandoc to LaTeX.  It seems to have some problem that PyMuPDF doesn't automatically repair.

**Comment by v217** [comment]
Thank you!
If OK, I think I will close this issue, since there is an easy workaround!
Thanks!
