### ISSUE TITLE
PySimpleGUI v4 is no longer available on PyPI

### ISSUE THREAD

**Issue by zeshuaro** [abarker/pdfCropMargins#59]
When installing the latest version with pip:

```
pip install pdfcropmargins==2.1.2
```

It fails to install with the following error:

```
ERROR: Ignored the following yanked versions: 2.7.0, 4.60.5
ERROR: Could not find a version that satisfies the requirement PySimpleGUI<=4.60.5,>=4.19.0.6 (from pdfcropmargins) (from versions: 5.0.0, 5.0.2, 5.0.3, 5.0.4, 5.0.5)
ERROR: No matching distribution found for PySimpleGUI<=4.60.5,>=4.19.0.6
```

**Comment by abarker** [comment]
Thanks for reporting the problem.  I'll try to push out a version with a vendorized copy of PySimpleGUI 4 soon.

**Comment by sinaatalay** [comment]
Could we make PySimpleGUI an optional dependency for people who are using pdfCropMargins in Python scripts only?

**Comment by abarker** [comment]
The new version is up as 2.1.3.  The final LGPL version of PySimpleGUI version 4 is now included with the distribution, removing the dependency.

**Comment by abarker** [comment]
PySimpleGUI used to be an optional dependency but it seemed like more bother than it was worth.  It now adds about 2M worth of extra disk usage, which doesn't seem too bad.

**Comment by zeshuaro** [comment]
Can confirm things are working now, thanks for the quick fix!
