### ISSUE TITLE
Bug in interactions of -e -u and -pg options

### ISSUE THREAD

**Issue by gybf** [abarker/pdfCropMargins#7]
Hi,

thanks for sharing this great app, however I found that sometimes the cropping just doesn't work as expected.
Specially when some **pages** are excluded (eg. the first one with a large picture cover) and the options **uniform** and **evenodd** are set - resulting in a seemingly uncropped top margin - at least with my test document.

I believe the bug lies in the main_pdfCropMargins.py modul starting at line 325 where a common bottom and top margin is searched after processing separately the even and odd pages:
```
min_bottom_margin = min([box[1] for box in combine_even_odd])
max_top_margin = max([box[3] for box in combine_even_odd])
```
Which means that the search is done on all the pages, including the otherwise excluded ones. I think the proper way of doing this would be something like this:
```
min_bottom_margin = min([box[1] for i, box in enumerate(combine_even_odd) if i in page_nums_to_crop])
max_top_margin = max([box[3] for i, box in enumerate(combine_even_odd) if i in page_nums_to_crop])
```

**Comment by abarker** [comment]
Yes, that interaction wasn't being handled correctly.  I've pushed a new version (0.1.4) to Github and PyPI which incorporates the fix.
