### ISSUE TITLE
Cosmetics: comment references non-existing function

### ISSUE THREAD

**Issue by assarbad** [abarker/pdfCropMargins#9]
In `manpage_data.py` you reference a function named `parseCommandLineArguments` (lines [31](https://github.com/abarker/pdfCropMargins/blob/master/src/pdfCropMargins/manpage_data.py#L31) and [36](https://github.com/abarker/pdfCropMargins/blob/master/src/pdfCropMargins/manpage_data.py#L36)) which should probably read `parse_command_line_arguments` instead.

It's merely a cosmetic issue, though.

**Comment by abarker** [comment]
Thanks, I've updated the comments to reflect the newer PEP8-style naming.
